# Generated by Django 3.1.7 on 2021-03-25 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotify', '0002_auto_20210324_2223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spotifytokens',
            name='access_token',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='spotifytokens',
            name='refresh_token',
            field=models.CharField(max_length=500),
        ),
    ]
